# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MP3EDJ.ui'
#
# Created: Thu Aug 07 01:18:46 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1260, 789)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Tuziibanez-Profesional-Red-Mp3-file.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.listWidget = QtGui.QListWidget(self.page_3)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout.addWidget(self.listWidget, 3, 1, 1, 2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.page_3)
        self.seekSlider.setMaximumSize(QtCore.QSize(16777099, 16777178))
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.verticalLayout_2.addWidget(self.seekSlider)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.Izvajalec = QtGui.QLabel(self.page_3)
        self.Izvajalec.setText(_fromUtf8(""))
        self.Izvajalec.setObjectName(_fromUtf8("Izvajalec"))
        self.horizontalLayout_6.addWidget(self.Izvajalec)
        self.Naslov = QtGui.QLabel(self.page_3)
        self.Naslov.setText(_fromUtf8(""))
        self.Naslov.setObjectName(_fromUtf8("Naslov"))
        self.horizontalLayout_6.addWidget(self.Naslov)
        self.BPM = QtGui.QLabel(self.page_3)
        self.BPM.setText(_fromUtf8(""))
        self.BPM.setObjectName(_fromUtf8("BPM"))
        self.horizontalLayout_6.addWidget(self.BPM)
        self.Key = QtGui.QLabel(self.page_3)
        self.Key.setText(_fromUtf8(""))
        self.Key.setObjectName(_fromUtf8("Key"))
        self.horizontalLayout_6.addWidget(self.Key)
        self.lcdNumber = QtGui.QLCDNumber(self.page_3)
        self.lcdNumber.setEnabled(True)
        self.lcdNumber.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setMouseTracking(False)
        self.lcdNumber.setAutoFillBackground(True)
        self.lcdNumber.setStyleSheet(_fromUtf8("color: rgb(18, 28, 45);"))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout_6.addWidget(self.lcdNumber)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 2, 1, 1)
        self.checkBoxBrisi = QtGui.QCheckBox(self.page_3)
        self.checkBoxBrisi.setObjectName(_fromUtf8("checkBoxBrisi"))
        self.gridLayout.addWidget(self.checkBoxBrisi, 0, 1, 1, 1)
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.page_3)
        self.volumeSlider.setMaximumSize(QtCore.QSize(100, 200))
        self.volumeSlider.setOrientation(QtCore.Qt.Vertical)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.gridLayout.addWidget(self.volumeSlider, 3, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setToolTip(_fromUtf8(""))
        self.progressBar.setStatusTip(_fromUtf8(""))
        self.progressBar.setAccessibleDescription(_fromUtf8(""))
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.MenuBar = QtGui.QMenuBar(MainWindow)
        self.MenuBar.setEnabled(True)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 1260, 26))
        self.MenuBar.setObjectName(_fromUtf8("MenuBar"))
        self.menuMP3EDJ = QtGui.QMenu(self.MenuBar)
        self.menuMP3EDJ.setTearOffEnabled(True)
        self.menuMP3EDJ.setObjectName(_fromUtf8("menuMP3EDJ"))
        self.menuAbout = QtGui.QMenu(self.MenuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuDirectory = QtGui.QMenu(self.MenuBar)
        self.menuDirectory.setObjectName(_fromUtf8("menuDirectory"))
        self.menuPlayer = QtGui.QMenu(self.MenuBar)
        self.menuPlayer.setObjectName(_fromUtf8("menuPlayer"))
        MainWindow.setMenuBar(self.MenuBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.ToolBar = QtGui.QToolBar(MainWindow)
        self.ToolBar.setStatusTip(_fromUtf8(""))
        self.ToolBar.setAutoFillBackground(False)
        self.ToolBar.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.174129 rgba(158, 223, 150, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.ToolBar.setMovable(True)
        self.ToolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.ToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ToolBar.setFloatable(False)
        self.ToolBar.setObjectName(_fromUtf8("ToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ToolBar)
        self.PlayBar = QtGui.QToolBar(MainWindow)
        self.PlayBar.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.174129 rgba(158, 223, 150, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.PlayBar.setMovable(True)
        self.PlayBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.PlayBar.setIconSize(QtCore.QSize(40, 50))
        self.PlayBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.PlayBar.setFloatable(False)
        self.PlayBar.setObjectName(_fromUtf8("PlayBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.PlayBar)
        self.MoveBar = QtGui.QToolBar(MainWindow)
        self.MoveBar.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.174129 rgba(158, 223, 150, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.MoveBar.setIconSize(QtCore.QSize(30, 30))
        self.MoveBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.MoveBar.setObjectName(_fromUtf8("MoveBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.MoveBar)
        self.actionMusic = QtGui.QAction(MainWindow)
        self.actionMusic.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Tuziibanez-Profesional-Red-Audio-folder.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMusic.setIcon(icon1)
        self.actionMusic.setIconVisibleInMenu(True)
        self.actionMusic.setObjectName(_fromUtf8("actionMusic"))
        self.actionGenre = QtGui.QAction(MainWindow)
        self.actionGenre.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Vargas21-Aquave-Metal-Music.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenre.setIcon(icon2)
        self.actionGenre.setObjectName(_fromUtf8("actionGenre"))
        self.actionPlaylist = QtGui.QAction(MainWindow)
        self.actionPlaylist.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Franksouza183-Fs-Mimetypes-playlist.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlaylist.setIcon(icon3)
        self.actionPlaylist.setObjectName(_fromUtf8("actionPlaylist"))
        self.actionStretch = QtGui.QAction(MainWindow)
        self.actionStretch.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Fatcow-Farm-Fresh-Application-side-expand.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStretch.setIcon(icon4)
        self.actionStretch.setObjectName(_fromUtf8("actionStretch"))
        self.actionRecorder = QtGui.QAction(MainWindow)
        self.actionRecorder.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Capital18-Capital-Suite-Drives-CD-Drive.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecorder.setIcon(icon5)
        self.actionRecorder.setObjectName(_fromUtf8("actionRecorder"))
        self.actionSplitter = QtGui.QAction(MainWindow)
        self.actionSplitter.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Semlabs-Web-Blog-Arrow-split-right.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplitter.setIcon(icon6)
        self.actionSplitter.setObjectName(_fromUtf8("actionSplitter"))
        self.actionEXIT = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Tuziibanez-Profesional-Red-Turn-off.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEXIT.setIcon(icon7)
        self.actionEXIT.setObjectName(_fromUtf8("actionEXIT"))
        self.actionSoftware = QtGui.QAction(MainWindow)
        self.actionSoftware.setObjectName(_fromUtf8("actionSoftware"))
        self.actionDeveloper = QtGui.QAction(MainWindow)
        self.actionDeveloper.setObjectName(_fromUtf8("actionDeveloper"))
        self.actionWebpage = QtGui.QAction(MainWindow)
        self.actionWebpage.setObjectName(_fromUtf8("actionWebpage"))
        self.actionNormalize = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Tuziibanez-Profesional-Red-Volume.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNormalize.setIcon(icon8)
        self.actionNormalize.setObjectName(_fromUtf8("actionNormalize"))
        self.actionConverter = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Custom-Icon-Design-Office-Export.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConverter.setIcon(icon9)
        self.actionConverter.setObjectName(_fromUtf8("actionConverter"))
        self.actionPlay = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Ahmadhania-Spherical-Play.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon10)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionPause = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Ahmadhania-Spherical-Stop.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon11)
        self.actionPause.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionNext = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Ahmadhania-Spherical-Next-track.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon12)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionPrev = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Ahmadhania-Spherical-Previous-track.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev.setIcon(icon13)
        self.actionPrev.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionPrev.setObjectName(_fromUtf8("actionPrev"))
        self.actionDelete = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/novaPredpona/Creative-Freedom-Shimmer-Document-Delete.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon14)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.actionDelete.setFont(font)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionTECHNO = QtGui.QAction(MainWindow)
        self.actionTECHNO.setCheckable(False)
        self.actionTECHNO.setObjectName(_fromUtf8("actionTECHNO"))
        self.actionHardTechno = QtGui.QAction(MainWindow)
        self.actionHardTechno.setObjectName(_fromUtf8("actionHardTechno"))
        self.actionHardCore = QtGui.QAction(MainWindow)
        self.actionHardCore.setObjectName(_fromUtf8("actionHardCore"))
        self.actionDrum_Bass = QtGui.QAction(MainWindow)
        self.actionDrum_Bass.setObjectName(_fromUtf8("actionDrum_Bass"))
        self.actionAdd_Folder = QtGui.QAction(MainWindow)
        self.actionAdd_Folder.setIcon(icon2)
        self.actionAdd_Folder.setObjectName(_fromUtf8("actionAdd_Folder"))
        self.actionAdd_Files = QtGui.QAction(MainWindow)
        self.actionAdd_Files.setObjectName(_fromUtf8("actionAdd_Files"))
        self.actionMove_all_files_to_root_folder = QtGui.QAction(MainWindow)
        self.actionMove_all_files_to_root_folder.setObjectName(_fromUtf8("actionMove_all_files_to_root_folder"))
        self.actionAdd_BPM_Tags_to_Files = QtGui.QAction(MainWindow)
        self.actionAdd_BPM_Tags_to_Files.setObjectName(_fromUtf8("actionAdd_BPM_Tags_to_Files"))
        self.actionAdd_KEY_Tags_to_Files = QtGui.QAction(MainWindow)
        self.actionAdd_KEY_Tags_to_Files.setObjectName(_fromUtf8("actionAdd_KEY_Tags_to_Files"))
        self.actionMove_Files_to_BPM_Sub_Folders = QtGui.QAction(MainWindow)
        self.actionMove_Files_to_BPM_Sub_Folders.setObjectName(_fromUtf8("actionMove_Files_to_BPM_Sub_Folders"))
        self.actionMove_Files_to_KEY_Sub_Folders = QtGui.QAction(MainWindow)
        self.actionMove_Files_to_KEY_Sub_Folders.setObjectName(_fromUtf8("actionMove_Files_to_KEY_Sub_Folders"))
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionRename_Files_by_ID3v2_Data = QtGui.QAction(MainWindow)
        self.actionRename_Files_by_ID3v2_Data.setObjectName(_fromUtf8("actionRename_Files_by_ID3v2_Data"))
        self.menuMP3EDJ.addAction(self.actionAdd_Files)
        self.menuMP3EDJ.addAction(self.actionAdd_Folder)
        self.menuMP3EDJ.addSeparator()
        self.menuMP3EDJ.addAction(self.actionOptions)
        self.menuMP3EDJ.addSeparator()
        self.menuMP3EDJ.addAction(self.actionEXIT)
        self.menuAbout.addAction(self.actionSoftware)
        self.menuAbout.addAction(self.actionDeveloper)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionWebpage)
        self.menuDirectory.addAction(self.actionMove_all_files_to_root_folder)
        self.menuDirectory.addSeparator()
        self.menuDirectory.addAction(self.actionAdd_BPM_Tags_to_Files)
        self.menuDirectory.addAction(self.actionAdd_KEY_Tags_to_Files)
        self.menuDirectory.addSeparator()
        self.menuDirectory.addAction(self.actionMove_Files_to_BPM_Sub_Folders)
        self.menuDirectory.addAction(self.actionMove_Files_to_KEY_Sub_Folders)
        self.menuDirectory.addSeparator()
        self.menuDirectory.addAction(self.actionRename_Files_by_ID3v2_Data)
        self.menuPlayer.addAction(self.actionPrev)
        self.menuPlayer.addAction(self.actionPlay)
        self.menuPlayer.addAction(self.actionNext)
        self.menuPlayer.addAction(self.actionPause)
        self.MenuBar.addAction(self.menuMP3EDJ.menuAction())
        self.MenuBar.addAction(self.menuDirectory.menuAction())
        self.MenuBar.addAction(self.menuPlayer.menuAction())
        self.MenuBar.addAction(self.menuAbout.menuAction())
        self.ToolBar.addAction(self.actionMusic)
        self.ToolBar.addAction(self.actionGenre)
        self.ToolBar.addAction(self.actionConverter)
        self.ToolBar.addAction(self.actionStretch)
        self.ToolBar.addAction(self.actionPlaylist)
        self.ToolBar.addAction(self.actionSplitter)
        self.ToolBar.addAction(self.actionNormalize)
        self.ToolBar.addAction(self.actionRecorder)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionEXIT)
        self.PlayBar.addAction(self.actionPrev)
        self.PlayBar.addAction(self.actionPlay)
        self.PlayBar.addAction(self.actionPause)
        self.PlayBar.addAction(self.actionNext)
        self.MoveBar.addAction(self.actionDelete)
        self.MoveBar.addAction(self.actionTECHNO)
        self.MoveBar.addAction(self.actionHardTechno)
        self.MoveBar.addAction(self.actionHardCore)
        self.MoveBar.addAction(self.actionDrum_Bass)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MP3EDJ", None))
        self.checkBoxBrisi.setText(_translate("MainWindow", "DELETE", None))
        self.progressBar.setFormat(_translate("MainWindow", "%p%", None))
        self.menuMP3EDJ.setTitle(_translate("MainWindow", "MP3EDJ", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuDirectory.setTitle(_translate("MainWindow", "Editor", None))
        self.menuPlayer.setTitle(_translate("MainWindow", "Player", None))
        self.ToolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.ToolBar.setToolTip(_translate("MainWindow", "uredi playliste", None))
        self.PlayBar.setWindowTitle(_translate("MainWindow", "PlayBar", None))
        self.MoveBar.setWindowTitle(_translate("MainWindow", "MoveBar", None))
        self.actionMusic.setText(_translate("MainWindow", "Music", None))
        self.actionMusic.setStatusTip(_translate("MainWindow", "Sort files by genre", None))
        self.actionGenre.setText(_translate("MainWindow", "Genre", None))
        self.actionPlaylist.setText(_translate("MainWindow", "Playlist", None))
        self.actionStretch.setText(_translate("MainWindow", "Stretch", None))
        self.actionRecorder.setText(_translate("MainWindow", "Recorder", None))
        self.actionSplitter.setText(_translate("MainWindow", "Splitter", None))
        self.actionEXIT.setText(_translate("MainWindow", "EXIT", None))
        self.actionSoftware.setText(_translate("MainWindow", "Software", None))
        self.actionDeveloper.setText(_translate("MainWindow", "Developer", None))
        self.actionWebpage.setText(_translate("MainWindow", "Webpage", None))
        self.actionNormalize.setText(_translate("MainWindow", "Normalize", None))
        self.actionConverter.setText(_translate("MainWindow", "Converter", None))
        self.actionPlay.setText(_translate("MainWindow", "Play", None))
        self.actionPause.setText(_translate("MainWindow", "Stop", None))
        self.actionPause.setShortcut(_translate("MainWindow", "Space", None))
        self.actionNext.setText(_translate("MainWindow", "Next", None))
        self.actionPrev.setText(_translate("MainWindow", "Previous", None))
        self.actionDelete.setText(_translate("MainWindow", "DELETE", None))
        self.actionDelete.setShortcut(_translate("MainWindow", "Del", None))
        self.actionTECHNO.setText(_translate("MainWindow", "TECHNO", None))
        self.actionTECHNO.setShortcut(_translate("MainWindow", "1", None))
        self.actionHardTechno.setText(_translate("MainWindow", "HardTechno", None))
        self.actionHardTechno.setShortcut(_translate("MainWindow", "2", None))
        self.actionHardCore.setText(_translate("MainWindow", "HardCore", None))
        self.actionHardCore.setShortcut(_translate("MainWindow", "3", None))
        self.actionDrum_Bass.setText(_translate("MainWindow", "Drum&Bass", None))
        self.actionDrum_Bass.setShortcut(_translate("MainWindow", "4", None))
        self.actionAdd_Folder.setText(_translate("MainWindow", "Add Folder", None))
        self.actionAdd_Files.setText(_translate("MainWindow", "Add Files", None))
        self.actionMove_all_files_to_root_folder.setText(_translate("MainWindow", "Move ALL Files to root Folder", None))
        self.actionAdd_BPM_Tags_to_Files.setText(_translate("MainWindow", "Add BPM Tags to Files", None))
        self.actionAdd_KEY_Tags_to_Files.setText(_translate("MainWindow", "Add KEY Tags to Files", None))
        self.actionMove_Files_to_BPM_Sub_Folders.setText(_translate("MainWindow", "Move Files to BPM Sub Folders", None))
        self.actionMove_Files_to_KEY_Sub_Folders.setText(_translate("MainWindow", "Move Files to KEY Sub Folders", None))
        self.actionOptions.setText(_translate("MainWindow", "Options", None))
        self.actionRename_Files_by_ID3v2_Data.setText(_translate("MainWindow", "Rename Files by ID3v2 Data", None))

from PyQt4 import phonon
import icons_rc
import play_rc
